Update everything else

diff --git a/.bin/a b/.bin/a
--- a/.bin/a
+++ b/.bin/a
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# 'a' = Asset builder (webpack, Gulp, Awe or npm as appropriate)
+# 'a' = Asset builder (webpack, Gulp or npm as appropriate)
 
-if dir="$(findup -f scripts/webpack.sh -o -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f awe.yaml -o -f package.json)"; then
+if dir="$(findup -f scripts/webpack.sh -o -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f package.json)"; then
 
     cd "$dir"
 
@@ -20,11 +20,6 @@ if dir="$(findup -f scripts/webpack.sh -o -f scripts/webpack.js -o -e gulpfile.j
         exec gulp "$@"
     fi
 
-    # Awe (http://awe.alberon.co.uk/ - Deprecated)
-    if [ -f awe.yaml ]; then
-        exec awe "$@"
-    fi
-
     # npm
     if [ -f package.json ]; then
         exec npm run "$@"
@@ -35,5 +30,5 @@ if dir="$(findup -f scripts/webpack.sh -o -f scripts/webpack.js -o -e gulpfile.j
 
 fi
 
-echo "Cannot find scripts/webpack.sh, scripts/webpack.js, gulpfile.js, awe.yaml or package.json" >&2
+echo "Cannot find scripts/webpack.sh, scripts/webpack.js, gulpfile.js or package.json" >&2
 exit 1
